//! PTY-обёртки над `portable-pty` для запуска интерактивных TUI-программ:
//! `tmux attach -t <session>` ([`spawn_tmux_attach`]) и `lazygit`
//! ([`spawn_lazygit`]).
//!
//! [`PtyHandle`] инкапсулирует master-сторону псевдотерминала, дочерний процесс
//! TUI и blocking I/O endpoint'ы (reader/writer). Чтение и запись по портам
//! `portable-pty` — синхронные (`std::io::Read` / `std::io::Write`), поэтому в
//! WebSocket-bridge (`src/ws.rs`) их следует оборачивать в
//! `tokio::task::spawn_blocking`.
//!
//! ### Жизненный цикл
//!
//! 1. [`spawn_tmux_attach`] / [`spawn_lazygit`] открывают PTY заданного размера,
//!    спавнят дочерний процесс с `TERM=xterm-256color` и возвращают
//!    [`PtyHandle`].
//! 2. Пока handle жив, ws.rs может бесконечно читать / писать байты и менять
//!    размер ([`PtyHandle::resize`]).
//! 3. При drop'e — [`Drop`] kill'ит ребёнка и waits на нём, чтобы избежать
//!    зомби-процессов.

use std::io::{Read, Write};
use std::path::{Path, PathBuf};

use anyhow::{anyhow, Context, Result};
use portable_pty::{native_pty_system, Child, CommandBuilder, MasterPty, PtySize};

/// Кастомные cable channels television, которые пишутся в
/// `~/.config/television/cable/forge-*.toml` при первом запуске Find-вкладки.
///
/// Отличия от дефолтных каналов tv:
/// - `--hidden` (dot-файлы вроде `.env.prod` попадают в результаты)
/// - `--no-ignore-vcs` (содержимое gitignored-файлов сканируется)
/// - `--glob/--exclude` для тяжёлых директорий (`.git`, `node_modules`, `target`)
///
/// Формат основан на дефолтных каналах television 0.15 (см. `tv update-channels`).
// Список «тяжёлых» директорий, которые мы исключаем из ВСЕХ forge-каналов.
// Покрывает Python venv (`.venv`/`venv`/`__pycache__`), Node (`node_modules`/
// `.next`/`.nuxt`), Rust (`target`), Go/PHP (`vendor`), общие build-output
// (`dist`/`build`), IDE/cache (`.idea`/`.vscode`/`.gradle`/`*.cache`).
//
// При изменении этого списка — bump версии в комменте файла, чтобы
// `ensure_forge_cable_channels` обнаружил stale-конфиг и перезаписал.
const FORGE_CABLE_FILES: &str = r#"# Generated by F.O.R.G.E. v3 — do not edit (regenerated on stale)
[metadata]
name = "forge-files"
description = "F.O.R.G.E. — file search (hidden + ignoring .gitignore)"
requirements = ["fd", "bat"]

[source]
command = [
  { name = "All",     run = "fd --type=file --hidden --no-ignore-vcs --exclude .git --exclude node_modules --exclude target --exclude .venv --exclude venv --exclude __pycache__ --exclude dist --exclude build --exclude vendor --exclude .next --exclude .nuxt --exclude .gradle --exclude .idea --exclude .vscode --exclude .mypy_cache --exclude .pytest_cache --exclude .ruff_cache --exclude .cargo --exclude '*.egg-info'" },
  { name = "Tracked", run = "fd --type=file --exclude .git --exclude node_modules --exclude target --exclude .venv --exclude venv --exclude __pycache__ --exclude dist --exclude build --exclude vendor --exclude .next --exclude .nuxt" },
]

[preview]
command = "bat -n --color=always {}"
env = { BAT_THEME = "ansi" }

[keybindings]
enter = "actions:edit"

[actions.edit]
description = "Open file in editor"
command = "${EDITOR:-vim} '{}'"
shell = "bash"
mode = "execute"
"#;

const FORGE_CABLE_TEXT: &str = r#"# Generated by F.O.R.G.E. v3 — do not edit (regenerated on stale)
[metadata]
name = "forge-text"
description = "F.O.R.G.E. — content search (hidden + ignoring .gitignore)"
requirements = ["rg", "bat"]

[source]
command = [
  { name = "All",     run = "rg . --no-heading --line-number --hidden --no-ignore-vcs --glob '!.git/' --glob '!node_modules/' --glob '!target/' --glob '!.venv/' --glob '!venv/' --glob '!__pycache__/' --glob '!dist/' --glob '!build/' --glob '!vendor/' --glob '!.next/' --glob '!.nuxt/' --glob '!.gradle/' --glob '!.idea/' --glob '!.vscode/' --glob '!.mypy_cache/' --glob '!.pytest_cache/' --glob '!.ruff_cache/' --glob '!.cargo/' --glob '!*.egg-info/' --colors 'match:fg:white' --colors 'path:fg:blue' --color=always" },
  { name = "Tracked", run = "rg . --no-heading --line-number --glob '!.git/' --glob '!node_modules/' --glob '!target/' --glob '!.venv/' --glob '!venv/' --glob '!__pycache__/' --glob '!dist/' --glob '!build/' --glob '!vendor/' --glob '!.next/' --glob '!.nuxt/' --colors 'match:fg:white' --colors 'path:fg:blue' --color=always" },
]
ansi = true
output = "{strip_ansi|split:\\::..2}"

[preview]
command = "bat -n --color=always '{strip_ansi|split:\\::0}'"
env = { BAT_THEME = "ansi" }
offset = '{strip_ansi|split:\::1}'

[ui]
preview_panel = { header = '{strip_ansi|split:\::..2}' }

[keybindings]
enter = "actions:edit"

[actions.edit]
description = "Open file in editor at line"
command = "${EDITOR:-vim} '+{strip_ansi|split:\\::1}' '{strip_ansi|split:\\::0}'"
shell = "bash"
mode = "execute"
"#;

const FORGE_CABLE_DIRS: &str = r#"# Generated by F.O.R.G.E. v2 — do not edit (regenerated on stale)
[metadata]
name = "forge-dirs"
description = "F.O.R.G.E. — directory search (hidden + ignoring .gitignore)"
requirements = ["fd"]

[source]
command = "fd --type=directory --hidden --no-ignore-vcs --exclude .git --exclude node_modules --exclude target --exclude .venv --exclude venv --exclude __pycache__ --exclude dist --exclude build --exclude vendor --exclude .next --exclude .nuxt --exclude .gradle --exclude .idea --exclude .vscode --exclude .mypy_cache --exclude .pytest_cache --exclude .ruff_cache --exclude .cargo --exclude '*.egg-info'"

[preview]
command = "ls -la {} 2>/dev/null"
"#;

const FORGE_CABLE_GIT_LOG: &str = r#"# Generated by F.O.R.G.E. — do not edit (regenerated on stale)
[metadata]
name = "forge-git-log"
description = "F.O.R.G.E. — browse git log"
requirements = ["git"]

[source]
command = "git log --oneline --color=always --decorate --all"
ansi = true
output = "{strip_ansi|split: :0}"

[preview]
command = "git show --color=always {strip_ansi|split: :0}"
"#;

/// Записывает кастомные forge-* cable channels в `~/.config/television/cable/`.
///
/// Перезаписывает существующие файлы (на случай обновления контента в наших
/// константах). Не падает фатально — если запись не удалась, tv просто не
/// найдёт канал и handle_tui_socket вернёт error-frame клиенту.
fn ensure_forge_cable_channels() -> Result<()> {
    let home = std::env::var_os("HOME")
        .ok_or_else(|| anyhow!("HOME env var not set"))?;
    let cable_dir = PathBuf::from(home).join(".config/television/cable");
    std::fs::create_dir_all(&cable_dir)
        .with_context(|| format!("failed to create {cable_dir:?}"))?;
    for (name, content) in [
        ("forge-files.toml", FORGE_CABLE_FILES),
        ("forge-text.toml", FORGE_CABLE_TEXT),
        ("forge-dirs.toml", FORGE_CABLE_DIRS),
        ("forge-git-log.toml", FORGE_CABLE_GIT_LOG),
    ] {
        let path = cable_dir.join(name);
        let needs_write = match std::fs::read_to_string(&path) {
            Ok(existing) => existing != content,
            Err(_) => true,
        };
        if needs_write {
            std::fs::write(&path, content)
                .with_context(|| format!("failed to write {path:?}"))?;
        }
    }
    Ok(())
}

/// Допустимое имя cable channel для television: только ASCII-alphanumeric,
/// `-` и `_`, длина 1..=64. Защита от инъекции произвольных аргументов
/// через query-параметр `?channel=...` (хотя `CommandBuilder::arg` уже не
/// шеллит, лишний валидатор полезен — например, чтобы исключить `--config`
/// и подобные флаги).
fn is_safe_channel_name(s: &str) -> bool {
    !s.is_empty()
        && s.len() <= 64
        && s.chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
}

/// Ищет бинарь в `$PATH` (упрощённый `which`). Возвращает `None`, если
/// исполняемого файла с таким именем нет ни в одном элементе PATH.
fn which_in_path(name: &str) -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    for dir in std::env::split_paths(&path) {
        let candidate = dir.join(name);
        if candidate.is_file() {
            return Some(candidate);
        }
    }
    None
}

/// Дескриптор живого PTY, в котором запущен `tmux attach`.
///
/// Поля:
/// - `master` — master-сторона PTY, на ней вызывается `resize()`.
/// - `child` — дескриптор дочернего процесса tmux. Drop kill'ит и ждёт его.
/// - `reader` — синхронный `Read`, с которого читается stdout PTY.
/// - `writer` — синхронный `Write`, в который пишется stdin PTY.
///
/// # Thread-safety
///
/// `MasterPty`, `Child`, `Read`, `Write` — `Send`, но *не обязательно*
/// `Sync`. На практике для обмена с асинхронным кодом в `ws.rs` мы перемещаем
/// reader/writer в `spawn_blocking`-таски, а `master` и `child` оставляем в
/// async-таске, который владеет [`PtyHandle`].
pub struct PtyHandle {
    /// Master-сторона псевдотерминала. На ней вызывается `resize`.
    pub master: Box<dyn MasterPty + Send>,
    /// Дочерний процесс tmux. Хранится в Option, чтобы Drop мог взять
    /// владение и сделать `kill` + `wait` без `unsafe`.
    child: Option<Box<dyn Child + Send + Sync>>,
    /// Blocking-reader stdout PTY. Может быть взят (`take_reader`) и
    /// перемещён в `spawn_blocking` для проксирования в WebSocket.
    reader: Option<Box<dyn Read + Send>>,
    /// Blocking-writer stdin PTY. Может быть взят (`take_writer`) и
    /// перемещён в `spawn_blocking` для проксирования из WebSocket.
    writer: Option<Box<dyn Write + Send>>,
}

impl PtyHandle {
    /// Меняет размер PTY. tmux получит SIGWINCH и перерисует layout.
    ///
    /// `cols`/`rows` — желаемые размеры в символах. `pixel_*` оставляем
    /// нулями: tmux ими не пользуется, как и большинство TUI.
    pub fn resize(&self, cols: u16, rows: u16) -> Result<()> {
        self.master
            .resize(PtySize {
                rows,
                cols,
                pixel_width: 0,
                pixel_height: 0,
            })
            .context("PtyHandle::resize: master.resize failed")
    }

    /// Забирает blocking-reader. Вызывается один раз при настройке bridge'а.
    /// Повторный вызов вернёт `None`.
    pub fn take_reader(&mut self) -> Option<Box<dyn Read + Send>> {
        self.reader.take()
    }

    /// Забирает blocking-writer. Вызывается один раз при настройке bridge'а.
    /// Повторный вызов вернёт `None`.
    ///
    /// Сейчас не используется напрямую (writer берётся через `writer_mut` под
    /// `Mutex<PtyHandle>` в `ws.rs`), но оставлен как часть симметричного API
    /// с `take_reader` — может пригодиться для будущих bridge'ей.
    #[allow(dead_code)]
    pub fn take_writer(&mut self) -> Option<Box<dyn Write + Send>> {
        self.writer.take()
    }

    /// Возвращает `&mut`-ссылку на writer (если он ещё не взят `take_writer`).
    ///
    /// Используется в `ws.rs` для записи WS-binary-байт в PTY без выноса
    /// writer'а наружу — вся блокирующая запись делается под `Mutex<PtyHandle>`
    /// внутри `spawn_blocking`.
    pub fn writer_mut(&mut self) -> Option<&mut Box<dyn Write + Send>> {
        self.writer.as_mut()
    }

    /// PID дочернего процесса tmux, если он ещё запущен.
    ///
    /// Используется в unit-тестах (`spawn_for_missing_session_does_not_panic`),
    /// поэтому в non-test сборке помечен как `allow(dead_code)`.
    #[allow(dead_code)]
    pub fn child_pid(&self) -> Option<u32> {
        self.child.as_ref().and_then(|c| c.process_id())
    }
}

/// Спавнит `tmux attach -t <session>` внутри нового PTY размера `cols × rows`.
///
/// Стартовое окружение:
/// - `TERM=xterm-256color` — обязательно, иначе tmux зайдёт в degraded-режим.
/// - Остальные переменные наследуются от текущего процесса (см. CommandBuilder
///   default behaviour).
///
/// Возвращает живой [`PtyHandle`]. Если такой сессии нет — PTY всё равно
/// откроется, а `tmux` напишет ошибку в stdout и вскоре завершится. Эту
/// ситуацию можно детектировать в ws.rs по EOF на reader'е.
pub fn spawn_tmux_attach(session: &str, cols: u16, rows: u16) -> Result<PtyHandle> {
    let pty_system = native_pty_system();
    let pair = pty_system
        .openpty(PtySize {
            rows,
            cols,
            pixel_width: 0,
            pixel_height: 0,
        })
        .context("openpty failed")?;

    let mut cmd = CommandBuilder::new("tmux");
    cmd.args(["attach", "-t", session]);
    cmd.env("TERM", "xterm-256color");

    let child = pair
        .slave
        .spawn_command(cmd)
        .with_context(|| format!("failed to spawn `tmux attach -t {session}`"))?;

    // После spawn slave-fd нам больше не нужен в текущем процессе: ребёнок
    // унаследовал fd. Закрываем slave явно, иначе master-side EOF не
    // придёт после exit'а ребёнка (на некоторых платформах). drop(slave).
    drop(pair.slave);

    let reader = pair
        .master
        .try_clone_reader()
        .context("master.try_clone_reader failed")?;
    let writer = pair
        .master
        .take_writer()
        .context("master.take_writer failed")?;

    Ok(PtyHandle {
        master: pair.master,
        child: Some(child),
        reader: Some(reader),
        writer: Some(writer),
    })
}

/// Спавнит `lazygit` внутри нового PTY размера `cols × rows` с заданным
/// рабочим каталогом (`cwd`).
///
/// Назначение:
/// - Используется в WebSocket-handler'е `/ws/lazygit` для интерактивного
///   git-UI прямо в браузере (через xterm.js во фронтенде).
///
/// Стартовое окружение:
/// - `cwd` — корень git-репозитория (или любой путь внутри него); lazygit сам
///   найдёт ближайший `.git`. Чаще всего это путь активного проекта из
///   `projects.rs`.
/// - `TERM=xterm-256color` — обязательно, иначе lazygit отрисует TUI без
///   цвета и с ASCII-bordertypes.
/// - Остальные переменные наследуются от текущего процесса (см. CommandBuilder
///   default behaviour) — это важно для `$HOME/.config/lazygit/config.yml`.
///
/// Обработка ошибок:
/// - Если бинарь `lazygit` не найден в `PATH`, `spawn_command` вернёт ошибку,
///   которую мы оборачиваем в `with_context`-сообщение с подсказкой об
///   установке (`brew install lazygit` / `pacman -S lazygit` и т.п.). Это
///   позволяет ws-handler'у показать осмысленный баннер пользователю вместо
///   общего `No such file or directory`.
///
/// Возвращает живой [`PtyHandle`]. EOF на reader'е сигнализирует, что
/// lazygit завершился (например, пользователь нажал `q`).
pub fn spawn_lazygit(cwd: &Path, cols: u16, rows: u16) -> Result<PtyHandle> {
    let pty_system = native_pty_system();
    let pair = pty_system
        .openpty(PtySize {
            rows,
            cols,
            pixel_width: 0,
            pixel_height: 0,
        })
        .context("openpty failed")?;

    let mut cmd = CommandBuilder::new("lazygit");
    cmd.cwd(cwd);
    cmd.env("TERM", "xterm-256color");

    let child = pair.slave.spawn_command(cmd).with_context(|| {
        format!(
            "failed to spawn `lazygit` in {:?}: lazygit not found in PATH, \
             install via `brew install lazygit` (macOS) or your distro's package manager",
            cwd
        )
    })?;

    // После spawn slave-fd нам больше не нужен в текущем процессе: ребёнок
    // унаследовал fd. Закрываем slave явно, иначе master-side EOF не
    // придёт после exit'а ребёнка (на некоторых платформах). drop(slave).
    drop(pair.slave);

    let reader = pair
        .master
        .try_clone_reader()
        .context("master.try_clone_reader failed")?;
    let writer = pair
        .master
        .take_writer()
        .context("master.take_writer failed")?;

    Ok(PtyHandle {
        master: pair.master,
        child: Some(child),
        reader: Some(reader),
        writer: Some(writer),
    })
}

/// Запускает `lazydocker` в указанном рабочем каталоге через `portable-pty` и
/// возвращает живой [`PtyHandle`].
///
/// Семантически идентичен [`spawn_lazygit`] — отличие только в бинаре
/// (`lazydocker` вместо `lazygit`). Используется ws-handler'ом
/// `lazydocker_attach` для отдельной TUI-вкладки управления Docker'ом.
///
/// Параметры:
/// - `cwd` — рабочий каталог. Для lazydocker может быть любой папкой; он
///   подключается к локальному docker-daemon'у вне зависимости от текущего
///   каталога. Обычно совпадает с cwd активного проекта.
/// - `cols`/`rows` — стартовый размер PTY (xterm grid).
///
/// Env / поведение совпадают с [`spawn_lazygit`]: `TERM=xterm-256color`,
/// остальное наследуется от текущего процесса (важно для
/// `$HOME/.config/lazydocker/config.yml`).
///
/// Обработка ошибок:
/// - Если бинарь `lazydocker` не найден в `PATH`, оборачиваем ошибку в
///   `with_context`-сообщение с подсказкой по установке. Это позволяет
///   ws-handler'у показать осмысленный баннер пользователю.
pub fn spawn_lazydocker(cwd: &Path, cols: u16, rows: u16) -> Result<PtyHandle> {
    let pty_system = native_pty_system();
    let pair = pty_system
        .openpty(PtySize {
            rows,
            cols,
            pixel_width: 0,
            pixel_height: 0,
        })
        .context("openpty failed")?;

    let mut cmd = CommandBuilder::new("lazydocker");
    cmd.cwd(cwd);
    cmd.env("TERM", "xterm-256color");

    let child = pair.slave.spawn_command(cmd).with_context(|| {
        format!(
            "failed to spawn `lazydocker` in {:?}: lazydocker not found in PATH. \
             Install: brew install lazydocker (macOS) | pacman -S lazydocker (Arch) | \
             https://github.com/jesseduffield/lazydocker",
            cwd
        )
    })?;

    drop(pair.slave);

    let reader = pair
        .master
        .try_clone_reader()
        .context("master.try_clone_reader failed")?;
    let writer = pair
        .master
        .take_writer()
        .context("master.take_writer failed")?;

    Ok(PtyHandle {
        master: pair.master,
        child: Some(child),
        reader: Some(reader),
        writer: Some(writer),
    })
}

/// Запускает `tv` (television) в указанном рабочем каталоге через
/// `portable-pty` и возвращает живой [`PtyHandle`].
///
/// Семантически идентичен [`spawn_lazygit`] — отличие только в бинаре
/// (`tv` вместо `lazygit`). Используется ws-handler'ом `telescope_attach`
/// для отдельной TUI-вкладки fuzzy-поиска по проекту.
///
/// Параметры:
/// - `cwd` — рабочий каталог. `tv` использует cwd как корень поиска
///   (файлы, директории, git-history и т.п.).
/// - `cols`/`rows` — стартовый размер PTY (xterm grid).
///
/// Env / поведение совпадают с [`spawn_lazygit`]: `TERM=xterm-256color`,
/// остальное наследуется от текущего процесса (важно для
/// `$HOME/.config/television/config.toml`).
///
/// Обработка ошибок:
/// - Если бинарь `tv` или его helper-утилиты (`fd`, `bat`) не найдены в
///   `PATH`, возвращаем понятную ошибку (frontend ловит её по подстроке
///   "not found" + имя бинаря и показывает install-banner).
///
/// **Helper-утилиты:** television использует `fd` для каналов `files` /
/// `dirs`, `bat` для preview и `rg` (ripgrep) для канала `text` (content
/// search). Без них UI поднимется, но панели будут крутить `command not
/// found`. Поэтому проверяем все три на старте и проваливаем spawn с одним
/// общим сообщением.
///
/// **Канал:** `channel` — логический режим (`files` / `text` / `dirs` /
/// `git-log`). Мы записываем кастомные cable channels television в
/// `~/.config/television/cable/forge-<channel>.toml` (на основе дефолтных,
/// но с `--hidden --no-ignore-vcs` для fd/rg) и запускаем `tv forge-<channel>`.
/// Это сильно быстрее ad-hoc-флагов: tv использует свой нативный source/output/
/// preview pipeline с ANSI parsing и multi-source (Ctrl+S переключает
/// Default/Hidden варианты внутри канала). По умолчанию — режим `files`.
pub fn spawn_television(
    cwd: &Path,
    cols: u16,
    rows: u16,
    channel: Option<&str>,
) -> Result<PtyHandle> {
    if which_in_path("tv").is_none() {
        return Err(anyhow!(
            "television (tv) not found in PATH. \
             Install all 4 helper tools: brew install television fd bat ripgrep (macOS) | \
             sudo pacman -S television fd bat ripgrep (Arch) | \
             cargo install --locked television fd-find bat ripgrep (any)"
        ));
    }
    let missing: Vec<&str> = ["fd", "bat", "rg"]
        .into_iter()
        .filter(|b| which_in_path(b).is_none())
        .collect();
    if !missing.is_empty() {
        return Err(anyhow!(
            "television helper tools not found in PATH: {}. \
             Without these `tv` will start, but file-search, preview and content-search panels won't work. \
             Install all 4 helpers: brew install television fd bat ripgrep (macOS) | \
             sudo pacman -S television fd bat ripgrep (Arch) | \
             cargo install --locked television fd-find bat ripgrep (any)",
            missing.join(", ")
        ));
    }

    let pty_system = native_pty_system();
    let pair = pty_system
        .openpty(PtySize {
            rows,
            cols,
            pixel_width: 0,
            pixel_height: 0,
        })
        .context("openpty failed")?;

    let chan = channel
        .map(|s| s.trim())
        .filter(|s| !s.is_empty() && is_safe_channel_name(s))
        .unwrap_or("files");

    // Гарантируем, что forge-<channel>.toml-каналы записаны в
    // ~/.config/television/cable/. Если уже есть — не перезаписываем.
    if let Err(e) = ensure_forge_cable_channels() {
        tracing::warn!(error = ?e, "ensure_forge_cable_channels failed; using fallback");
    }
    let forge_channel = format!("forge-{}", chan);

    let mut cmd = CommandBuilder::new("tv");
    cmd.arg(&forge_channel);
    cmd.cwd(cwd);
    cmd.env("TERM", "xterm-256color");

    let chan_owned = chan.to_string();
    let child = pair.slave.spawn_command(cmd).with_context(|| {
        format!(
            "failed to spawn `tv {}` in {:?}: television (tv) not found in PATH. \
             Install: brew install television fd bat ripgrep (macOS) | \
             cargo install --locked television fd-find bat ripgrep | \
             https://github.com/alexpasmantier/television",
            chan_owned, cwd
        )
    })?;

    drop(pair.slave);

    let reader = pair
        .master
        .try_clone_reader()
        .context("master.try_clone_reader failed")?;
    let writer = pair
        .master
        .take_writer()
        .context("master.take_writer failed")?;

    Ok(PtyHandle {
        master: pair.master,
        child: Some(child),
        reader: Some(reader),
        writer: Some(writer),
    })
}

impl Drop for PtyHandle {
    /// Гарантированно kill'ит и reap'ает ребёнка, чтобы не оставить зомби.
    /// Ошибки игнорируем — Drop не должен паниковать.
    fn drop(&mut self) {
        if let Some(mut child) = self.child.take() {
            let _ = child.kill();
            let _ = child.wait();
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Проверяет, что PTY открывается даже для несуществующей сессии:
    /// процесс tmux запустится и быстро завершится, но spawn должен пройти.
    /// Тест безвреден, даже если tmux не установлен — тогда вернётся Err и
    /// ассертом мы это явно проверяем (но не валим тест).
    #[test]
    fn spawn_for_missing_session_does_not_panic() {
        match spawn_tmux_attach("definitely-does-not-exist-xyz", 80, 24) {
            Ok(handle) => {
                // Просто проверяем, что pid у нас есть (или None — оба ОК).
                let _ = handle.child_pid();
                // Drop сделает kill+wait — ребёнок завершится.
            }
            Err(e) => {
                // Допустимо: tmux может отсутствовать в test-окружении.
                eprintln!("spawn_tmux_attach failed (tmux missing?): {e:#}");
            }
        }
    }
}
